### ISSUE TITLE
Script doesn't find the data files

### ISSUE THREAD

**Issue by vilsaira** [KUL-Radneuron/KUL_VBG#3]
Hi,

Here is the running command I tried:
` ~/KUL_VBG/KUL_VBG.sh -p pat001 -a sub-pat001.nii.gz -l sub-01_ses-001_roCFM.nii.gz -z T1 -o uVBG -t -F -n 6 -B 1`

I ran the script in the directory where I had the data. I also tried to give the full path and it gave the same error below:

`Inputs are -p  pat001  -lesion  sub-01_ses-001_roCFM.nii.gz  -lesion_space  T1`
`/root/KUL_VBG/KUL_VBG.sh: line 283: : No such file or directory`
` T1 images provided as sub-pat001.nii.gz`
`/root/KUL_VBG/KUL_VBG.sh: line 398: : No such file or directory`
` Preproc dir is <fullpath>/VBG_out/proc_VBG/sub-pat001 and output dir is uVBG/output_VBG/sub-pat001`
` You are using KUL_VBG.sh version 0.48_08022021`

` You have specified HD-BET for brain extraction, please make sure it is called correctly from within KUL_VBG`
` In case of BET problems see lines 1124 - 1200`

`update function path to reflect funciton name line 514`

Ideas how to fix this? I should have all the prerequisites installed and I also tried with -B 2 but it gave again the same error expect for the HD-BET part.

Lesion mask and T1 volumes are identical so that shouldn't be the problem.

**Comment by vilsaira** [comment]
Got forward, the script required replacing ${prep_log} with "${prep_log}" in few locations and adding the script location to the path.

**Comment by Rad-dude** [comment]
Hi vilsaira,

I was indeed going to suggest adding it to path first.

this is line 283: echo "Inputs are -p  ${subj}  -lesion  ${L_mask}  -lesion_space  ${L_mask_space}" >> ${prep_log}
and this is line 398: echo " We found T1 WIs ${T1_orig}" >> ${prep_log}

Indeed as you suggest this was due to incorrect referral to ${prep_log}.

I'm now fixing this and will push the fixed version.

Thanks for your feedback.

**Comment by Rad-dude** [comment]
I've just pushed the fixed version if you would like to clone and try it out.
We can keep this issue open till then also.

Best,
AR

**Comment by vilsaira** [comment]
Thanks, pulled the new version and it seems to work out of the box (with ANTs bet). I didn't get the HD-BET working, unfortunately.

**Comment by Rad-dude** [comment]
Glad to hear it's working, for help with HD-BET maybe check out their github repo for installation instructions (https://github.com/MIC-DKFZ/HD-BET), HD-BET has a number of dependencies that are listed also on their page.

You can install it via a conda virtual environment for example if it's conflicting with any other packages in your default python environment.

I will close this issue for now since the main issue is resolved.
